# Site settings
title: Nathan Robinson
email: nrobinson2000@me.com
description: > # this means to ignore newlines until "baseurl:"
  Nathan Robinson

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nrobinson.me" # the base hostname & protocol for your site
twitter_username: nrobinson2000
github_username:  nrobinson2000
insta_username: nrobinson2000

# Build settings
markdown: kramdown
